### ISSUE TITLE
Unclosed regular expression warnings

### ISSUE THREAD

**Issue by fczuardi** [zedapp/jsx-mode#1]
Maybe this issue is a duplicate or is filed in the wrong place, but the default javscript/jsx linter gives me syntax error warnings on pretty much any .jsx file, example:

``` jsx
var React = require('react');

var TestComponent = React.creatClass({
    render: function(){
        <p>foo</p>
    }
});
React.render(<TestComponent />, document.body);
```

Will display the red "X" icon on the line of `<p>foo</p>`

**Comment by zefhemel** [comment]
Isn't that actually a syntax mistake? Should there be a `return` statement there? e.g. `return <p>foo</p>;` perhaps with parentheses around the tags even.

**Comment by fczuardi** [comment]
My bad, the example should've been:

``` jsx
var React = require('react');

var TestComponent = React.creatClass({
    render: function(){
        return(
            <p>foo</p>
        );
    }
});
React.render(<TestComponent />, document.body);
```

But the problem is the same, event if I copy/paste facebooks hello world example from http://facebook.github.io/react/docs/getting-started.html

``` jsx
var React = require('react');

React.render(
  <h1>Hello, world!</h1>,
  document.getElementById('example')
);
```

The problem persist. What does zed use to check the syntax? is it jsxhint? what version? because by googling the error the first result is this thread: https://github.com/STRML/JSXHint/issues/28

**Comment by fczuardi** [comment]
Ok, I tracked the problem:

The thing is, the jsx transform that is supposed to run before sending the code to jshint currently **only runs if a jsx docblock is present**, so:

``` jsx
/** @jsx React.createElement */
var React = require('react');

var TestComponent = React.creatClass({
    render: function(){
        return(
            <p>foo</p>
        );
    }
});
React.render(<TestComponent />, document.body);
```

Will not present any red warnings to the user.

The fix would be to remove the docblock requirement for files with .jsx extension, because since React 0.12 this is no longer a needed, see http://facebook.github.io/react/blog/2014/10/16/react-v0.12-rc1.html#the-jsx-pragma-is-gone

**Comment by fczuardi** [comment]
This comment line gives a hint:

https://github.com/zedapp/jsx-mode/blob/master/transform.js#L9952

Maybe upgrading the jsxtransform to a recent would fix this, I can't tell since I dont know how this transfor.js file is generated

**Comment by fczuardi** [comment]
A quick patch/workaround is to replace line #9952 with

``` diff
diff --git a/transform.js b/transform.js
index 1e29516..cc61fe3 100644
--- a/transform.js
+++ b/transform.js
@@ -9951,7 +9951,7 @@ function visitReactTag(traverse, object, path, state) {
 visitReactTag.test = function(object, path, state) {
   // only run react when react @jsx namespace is specified in docblock
   var jsx = utils.getDocblock(state).jsx;
-  return object.type === Syntax.XJSElement && jsx && jsx.length;
+  return object.type === Syntax.XJSElement;
 };

 exports.visitorList = [
```

A proper fix would maybe be update to a newer version of the library this code is based on.

**Comment by zefhemel** [comment]
Interesting, I'll upgrade the JSX transformer module to a more recent version. Hold tight.

**Comment by zefhemel** [comment]
Updated, should be fixed now. Thanks for reporting!

**Comment by dkafle** [comment]
Still getting `Unclosed regular expression` warning message even with the latest code.

**Comment by samuraii** [comment]
true story

**Comment by cristian-sima** [comment]
still here
